### ISSUE TITLE
疑似核心BUG，批量下载时gRPC报错

### ISSUE THREAD

**Issue by YongQI233** [JiJiDown/Tracker#17]
**描述错误**
Jithon下载up主合集视频时点击“下载全部”，在第四个视频时遇到卡进度问题。客户端回显报错如附件所示。似乎是JiDown核心问题。
另：
![XK34XSIR(Z$A}MEVMA9ULQ](https://github.com/JiJiDown/Tracker/assets/85042877/005f896f-0867-4a15-ac1e-d2cab465ef16)
![image](https://github.com/JiJiDown/Tracker/assets/85042877/d723ad66-0055-4984-be6e-8bae2c1e4bf7)

问题描述不正确或缺少信息会要求补充信息, 7 天内未补充会被关闭问题。

**软件信息**

 - 你使用的是什么系统:  Windows 11
 - 软件版本号: **JiThon v3.1-Beta** && **JiJiDownCore-win64.exe**（‎‎2023‎年‎7‎月‎12‎日，‏‎16:24:40版）
 - (可选) 下载问题请添加视频地址: https://www.bilibili.com/video/BV1pd4y1N7o6/?spm_id_from=333.337.top_right_bar_window_default_collection.content.click&vd_source=45b99812903c4d01d7b7c494f6a6176a
**重现**
重现此行为的步骤:
使用JiThon如描述错误板块执行即可复现，本操作至少在一台设备初始发现，一台设备复现，复现时有三次均为此结果

1. 转到 Jithon Web 输入合集视频地址
2. 点击 ‘下载全部’
3. 待下载四个、五个左右时出现错误
4. 看到错误被报告

**预期行为**
怀疑是gRPC错误，关键点位于“客户端回显”中的gRPC报错中的
status = StatusCode.FAILED_PRECONDITION：摘抄的对本错误code的解释：客户端在调用服务端的方法时，没有满足一些先决条件，导致服务端拒绝执行请求。例如，如果客户端要求删除一个非空的目录，服务端会返回这个错误码。
（我对gRPC了解不深，仅供参考，看个乐呵）

**附加日志**

日志获取方法请参阅 [唧唧 2.0 如何 Debug | 调试](http://client.jijidown.com/quick_start/how_to_debug/)

```log

1.[log_2023_07_19_20_25_40.log]
视频编号: av344209894
操作流程: JiThon 下载全部
日志：
time="2023-07-19 20:25:40" level=info msg="Welcome to JiJiDownCore git.r282.1f34dc07 windows/amd64 with go1.20.4"
time="2023-07-19 20:25:40" level=info msg="Built on 2023-06-01 14:45:49"
time="2023-07-19 20:25:40" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-07-19 20:25:40" level=info msg="Configuration file location: C:\\Users\\a\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-07-19 20:25:41" level=warning msg="missing file: JiJiDownForReWPF.exe"
time="2023-07-19 20:25:41" level=warning msg="missing file: grpc_csharp_ext.x64.dll"
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
time="2023-07-19 20:25:55" level=error msg="AllQuality It's a premium feature"
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/05/72/794207205/794207205-1-30121.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/05/72/794207205/794207205-1-30121.m4s"
> Received: os => [], device => []
> Received: os => [], device => []
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/05/72/794207205/794207205-1-30280.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/05/72/794207205/794207205-1-30280.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/96/77/794217796/794217796-1-30066.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/96/77/794217796/794217796-1-30066.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://cn-jstz-cu-01-07.bilivideo.com/upgcxcode/96/77/794217796/794217796-1-30280.m4s"
time="2023-07-19 20:25:59" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/96/77/794217796/794217796-1-30280.m4s"
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
> Received: os => [], device => []
（省略以上重复内容*n）
time="2023-07-19 20:27:26" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:27:26" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:27:26" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/76/08/794200876/794200876-1-30121.m4s"
time="2023-07-19 20:27:26" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/76/08/794200876/794200876-1-30121.m4s"
time="2023-07-19 20:27:26" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:27:26" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/76/08/794200876/794200876-1-30280.m4s"
time="2023-07-19 20:27:26" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:27:26" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/76/08/794200876/794200876-1-30280.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://upos-sz-mirrorhwb.bilivideo.com/upgcxcode/91/04/794200491/794200491-1-30121.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/91/04/794200491/794200491-1-30121.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/91/04/794200491/794200491-1-30280.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/91/04/794200491/794200491-1-30280.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://cn-hncs-cu-01-05.bilivideo.com/upgcxcode/07/21/794202107/794202107-1-30121.m4s"
time="2023-07-19 20:28:05" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:05" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/07/21/794202107/794202107-1-30121.m4s"
time="2023-07-19 20:28:06" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:06" level=error msg="JDM: fetch error: https://upos-sz-mirror08c.bilivideo.com/upgcxcode/07/21/794202107/794202107-1-30280.m4s"
time="2023-07-19 20:28:06" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:06" level=error msg="JDM: fetch error: https://cn-hncs-cu-01-05.bilivideo.com/upgcxcode/07/21/794202107/794202107-1-30280.m4s"
time="2023-07-19 20:28:36" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:36" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:36" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/85/29/794202985/794202985-1-30121.m4s"
time="2023-07-19 20:28:36" level=error msg="JDM: fetch error: https://cn-sxty-cu-03-08.bilivideo.com/upgcxcode/85/29/794202985/794202985-1-30121.m4s"
time="2023-07-19 20:28:36" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:36" level=error msg="JDM: fetch error: https://cn-sxty-cu-03-08.bilivideo.com/upgcxcode/85/29/794202985/794202985-1-30280.m4s"
time="2023-07-19 20:28:36" level=error msg="JDM: RoundTripper error: context canceled"
time="2023-07-19 20:28:36" level=error msg="JDM: fetch error: https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/85/29/794202985/794202985-1-30280.m4s"

2.[log_2023_07_19_20_28_55.log]
视频编号: av344209894
操作流程: JiThon 下载全部 （继1.[log_2023_07_19_20_25_40.log]后生成的另一log文件）
日志：
time="2023-07-19 20:28:55" level=info msg="Welcome to JiJiDownCore git.r282.1f34dc07 windows/amd64 with go1.20.4"
time="2023-07-19 20:28:55" level=info msg="Built on 2023-06-01 14:45:49"
time="2023-07-19 20:28:55" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-07-19 20:28:55" level=info msg="Configuration file location: C:\\Users\\a\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-07-19 20:28:56" level=warning msg="missing file: JiJiDownForReWPF.exe"
time="2023-07-19 20:28:56" level=warning msg="missing file: grpc_csharp_ext.x64.dll"
> Received: os => [], device => []
time="2023-07-19 20:30:28" level=error msg="task not found"

3.[客户端回显.txt]
2023-07-19 20:25:37.658 | INFO     | core:<module>:41 - 启动grpc,地址为localhost:64000
2023-07-19 20:25:37.659 | INFO     | core:<module>:43 - 设置SDK
2023-07-19 20:25:37.660 | INFO     | core:<module>:47 - 设置路径
2023-07-19 20:25:37.674 | INFO     | __main__:<module>:542 - 自动更新核心
2023-07-19 20:25:37.679 | INFO     | core:get_sha265:229 - 获取云端核心数据,检查更新
2023-07-19 20:25:39.937 | INFO     | core:update_core:306 - 核心目前是最新版本
2023-07-19 20:25:39.938 | WARNING  | core:check_ffmpeg:56 - 未找到ffmpeg,下载的视频可能无法合成
2023-07-19 20:25:39.938 | INFO     | __main__:<module>:549 - 主程序启动,如未自动跳转请打开http://127.0.0.1:8080
Running on http://127.0.0.1:8080/
2023-07-19 20:25:40.369 | INFO     | __main__:main:422 - 网页服务器启动
2023-07-19 20:25:40.369 | INFO     | __main__:main:425 - 启动核心
2023-07-19 20:25:40.371 | INFO     | __main__:start_core:41 - windows核心已启动
2023-07-19 20:25:40.372 | DEBUG    | core:get_user_info:150 - 尝试获取用户登录状态
2023-07-19 20:25:42.896 | INFO     | __main__:main:450 - 当前服务器名称 🔥 唧唧 2.0 开发版 ☆Kira~
2023-07-19 20:25:42.896 | INFO     | __main__:main:451 - 当前操作系统名称 Windows 11 22H2 x64
2023-07-19 20:25:42.897 | DEBUG    | __main__:main:459 - 核心已连接
2023-07-19 20:25:42.898 | DEBUG    | __main__:main:466 - 当前登录用户: YongQI233 [年度大会员]
2023-07-19 20:25:53.881 | DEBUG    | core:info:421 - 发送视频信息查询 https://www.bilibili.com/video/BV1pd4y1N7o6/?spm_id_from=333.337.top_right_bar_window_default_collection.content.click&vd_source=45b99812903c4d01d7b7c494f6a6176a
2023-07-19 20:25:55.574 | DEBUG    | core:quality:515 - 发送清晰度查询 bvid=BV1pd4y1N7o6 cid=794207205
2023-07-19 20:25:55.576 | WARNING  | core:quality:519 - 无唧唧会员权限
2023-07-19 20:25:55.579 | WARNING  | core:quality:520 - 无法获取分辨率列表
2023-07-19 20:25:58.779 | DEBUG    | __main__:print_video_info:278 - 所有视频被选中
2023-07-19 20:25:59.000 | INFO     | __main__:watch_status:303 - 1999.宝莲灯.85分钟 加入任务监视阵列
2023-07-19 20:25:59.198 | INFO     | __main__:watch_status:303 - 2012.大闹天宫.92分钟 加入任务监视阵列
2023-07-19 20:25:59.400 | INFO     | __main__:watch_status:303 - 1996.日月潭.20分钟 加入任务监视阵列
2023-07-19 20:25:59.575 | INFO     | __main__:watch_status:303 - 1993.小和尚之游方僧.10分钟 加入任务监视阵列
2023-07-19 20:25:59.762 | INFO     | __main__:watch_status:303 - 1989.西游记之三件宝贝.25分钟 加入任务监视阵列
2023-07-19 20:25:59.960 | INFO     | __main__:watch_status:303 - 1988.螳螂捕蝉.5分钟 加入任务监视阵列
2023-07-19 20:26:00.182 | INFO     | __main__:watch_status:303 - 1988.山水情.19分钟 加入任务监视阵列
2023-07-19 20:26:00.626 | INFO     | __main__:watch_status:303 - 1988.不射之射.25分钟 加入任务监视阵列
2023-07-19 20:26:01.132 | INFO     | __main__:watch_status:303 - 1986.超级肥皂.6分钟 加入任务监视阵列
2023-07-19 20:26:01.916 | INFO     | __main__:watch_status:303 - 1985.抢枕头.18分钟 加入任务监视阵列
2023-07-19 20:26:02.415 | INFO     | __main__:watch_status:303 - 1983.鹬蚌相争.10分钟 加入任务监视阵列
2023-07-19 20:26:02.932 | INFO     | __main__:watch_status:303 - 1983.天书奇谭.89分钟 加入任务监视阵列
2023-07-19 20:26:03.454 | INFO     | __main__:watch_status:303 - 1983.小八戒.20分钟 加入任务监视阵列
2023-07-19 20:26:04.090 | INFO     | __main__:watch_status:303 - 1983.松鼠理发师.10分钟 加入任务监视阵列
2023-07-19 20:26:04.543 | INFO     | __main__:watch_status:303 - 1983.狐狸送葡萄.17分钟 加入任务监视阵列
2023-07-19 20:26:05.205 | INFO     | __main__:watch_status:303 - 1983.猴子钓鱼.16分钟 加入任务监视阵列
2023-07-19 20:26:05.768 | INFO     | __main__:watch_status:303 - 1982.小熊猫学木匠.17分钟 加入任务监视阵列
2023-07-19 20:26:06.141 | INFO     | __main__:watch_status:303 - 1982.鹿铃.20分钟 加入任务监视阵列
2023-07-19 20:26:06.733 | INFO     | __main__:watch_status:303 - 1982.老虎学艺.18分钟 加入任务监视阵列
2023-07-19 20:26:07.294 | INFO     | __main__:watch_status:303 - 1982.狼来了.17分钟 加入任务监视阵列
2023-07-19 20:26:07.791 | INFO     | __main__:watch_status:303 - 1982.曹冲称象.16分钟 加入任务监视阵列
2023-07-19 20:26:08.338 | INFO     | __main__:watch_status:303 - 1981.真假李逵.18分钟 加入任务监视阵列
2023-07-19 20:26:08.881 | INFO     | __main__:watch_status:303 - 1981.抬驴.17分钟 加入任务监视阵列
2023-07-19 20:26:09.577 | INFO     | __main__:watch_status:303 - 1981.三个和尚.20分钟 加入任务监视阵列
2023-07-19 20:26:10.254 | INFO     | __main__:watch_status:303 - 1981.人参果_孙悟空偷吃人参果.45分钟 加入任务监视阵列
2023-07-19 20:26:10.434 | INFO     | __main__:watch_status:303 - 1981.南郭先生.18分钟 加入任务监视阵列
2023-07-19 20:26:11.023 | INFO     | __main__:watch_status:303 - 1981.崂山道士.25分钟 加入任务监视阵列
2023-07-19 20:26:11.665 | INFO     | __main__:watch_status:303 - 1981.九色鹿_鹿王本生.25分钟 加入任务监视阵列
2023-07-19 20:26:12.466 | INFO     | __main__:watch_status:303 - 1981.猴子捞月.10分钟 加入任务监视阵列
2023-07-19 20:26:12.994 | INFO     | __main__:watch_status:303 - 1980.张飞审瓜.25分钟 加入任务监视阵列
2023-07-19 20:26:13.718 | INFO     | __main__:watch_status:303 - 1980.雪孩子.21分钟 加入任务监视阵列
2023-07-19 20:26:14.463 | INFO     | __main__:watch_status:303 - 1980.我的朋友小海豚.18分钟 加入任务监视阵列
2023-07-19 20:26:14.936 | INFO     | __main__:watch_status:303 - 1980.三只狼.9分钟 加入任务监视阵列
2023-07-19 20:26:15.603 | INFO     | __main__:watch_status:303 - 1980.老狼请客.10分钟 加入任务监视阵列
2023-07-19 20:26:16.340 | INFO     | __main__:watch_status:303 - 1979.愚人买鞋.9分钟 加入任务监视阵列
2023-07-19 20:26:17.195 | INFO     | __main__:watch_status:303 - 1979.熊猫百货商店.16分钟 加入任务监视阵列
2023-07-19 20:26:17.819 | INFO     | __main__:watch_status:303 - 1979.哪吒闹海.61分钟 加入任务监视阵列
2023-07-19 20:26:18.330 | INFO     | __main__:watch_status:303 - 1979.好猫咪咪.20分钟 加入任务监视阵列
2023-07-19 20:26:19.178 | INFO     | __main__:watch_status:303 - 1978.狐狸打猎人.17分钟 加入任务监视阵列
2023-07-19 20:26:19.672 | INFO     | __main__:watch_status:303 - 1964.大闹天宫.111分钟 加入任务监视阵列
2023-07-19 20:26:20.523 | INFO     | __main__:watch_status:303 - 1964.半夜鸡叫.16分钟 加入任务监视阵列
2023-07-19 20:26:20.829 | INFO     | __main__:watch_status:303 - 1963.牧笛.21分钟 加入任务监视阵列
2023-07-19 20:26:21.483 | INFO     | __main__:watch_status:303 - 1962.没头脑和不高兴.22分钟 加入任务监视阵列
2023-07-19 20:26:22.436 | INFO     | __main__:watch_status:303 - 1962.等明天.15分钟 加入任务监视阵列
2023-07-19 20:26:23.184 | INFO     | __main__:watch_status:303 - 1961.人参娃娃.26分钟 加入任务监视阵列
2023-07-19 20:26:23.935 | INFO     | __main__:watch_status:303 - 1960.小蝌蚪找妈妈.16分钟 加入任务监视阵列
2023-07-19 20:26:24.444 | INFO     | __main__:watch_status:303 - 1959.渔童.23分钟 加入任务监视阵列
2023-07-19 20:26:25.067 | INFO     | __main__:watch_status:303 - 1956.骄傲的将军.25分钟 加入任务监视阵列
2023-07-19 20:26:25.641 | INFO     | __main__:watch_status:303 - 1955.东郭先生.11分钟 加入任务监视阵列
2023-07-19 20:27:20.354 | SUCCESS  | __main__:watch_status:343 - 2012.大闹天宫.92分钟 下载完成
2023-07-19 20:28:02.625 | SUCCESS  | __main__:watch_status:343 - 1996.日月潭.20分钟 下载完成
2023-07-19 20:28:04.255 | SUCCESS  | __main__:watch_status:343 - 1999.宝莲灯.85分钟 下载完成
2023-07-19 20:28:33.931 | SUCCESS  | __main__:watch_status:343 - 1993.小和尚之游方僧.10分钟 下载完成
2023-07-19 20:28:47.285 | SUCCESS  | __main__:watch_status:343 - 1988.螳螂捕蝉.5分钟 下载完成
panic: runtime error: index out of range [0] with length 0

goroutine 442 [running]:
github.com/JiJiDown/JiJiDownCore-go/common/jdm.(*JDMTask).NewSession(0xc0001d6770, {0x0, 0x0, 0x0}, {0xc0006665e0, 0x20}, 0x1)
        github.com/JiJiDown/JiJiDownCore-go/common/jdm/jdm_func_pub.go:18 +0x26f
github.com/JiJiDown/JiJiDownCore-go/core/download.startTask(0xc0001f5200)
        github.com/JiJiDown/JiJiDownCore-go/core/download/download_queue.go:92 +0x232
github.com/JiJiDown/JiJiDownCore-go/core/download.DownloadQueueAdd(0xc0001f5200)
        github.com/JiJiDown/JiJiDownCore-go/core/download/download_queue.go:60 +0x42e
github.com/JiJiDown/JiJiDownCore-go/hub/rpc.(*taskServer).New.func2()
        github.com/JiJiDown/JiJiDownCore-go/hub/rpc/task.go:85 +0x7b
created by github.com/JiJiDown/JiJiDownCore-go/hub/rpc.(*taskServer).New
        github.com/JiJiDown/JiJiDownCore-go/hub/rpc/task.go:77 +0x3df
2023-07-19 20:28:50.573 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.574 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.574 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.576 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
（省略以上重复内容*34）
2023-07-19 20:28:50.578 | ERROR    | __main__:start_core:50 - 核心关闭,尝试重启,检查异常信息
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:50.578 | ERROR    | __main__:watch_status:352 - 线程出现错误,无法获取下载进度
2023-07-19 20:28:55.604 | INFO     | __main__:start_core:41 - windows核心已启动
Unhandled error in pywebio app
Traceback (most recent call last):
  File "pywebio\session\threadbased.py", line 261, in run
  File "pywebio\output.py", line 839, in click_callback
  File "app.py", line 322, in <lambda>
  File "app.py", line 297, in resume_task
  File "core.py", line 598, in patch_resume_task
  File "grpc\_channel.py", line 1030, in __call__
  File "grpc\_channel.py", line 910, in _end_unary_response_blocking
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "task not found"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"task not found", grpc_status:9, created_time:"2023-07-19T12:30:28.177651455+00:00"}"
>

4.[web报错.txt]
Traceback (most recent call last):
  File "pywebio\session\threadbased.py", line 261, in run
  File "pywebio\output.py", line 839, in click_callback
  File "app.py", line 322, in <lambda>
  File "app.py", line 297, in resume_task
  File "core.py", line 598, in patch_resume_task
  File "grpc\_channel.py", line 1030, in __call__
  File "grpc\_channel.py", line 910, in _end_unary_response_blocking
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "task not found"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"task not found", grpc_status:9, created_time:"2023-07-19T12:30:28.177651455+00:00"}"
>
```

注：log中的用户名已用'a'替换

**Comment by xiahuaijia** [comment]
请按要求提供日志

**Comment by YongQI233** [comment]
> 请按要求提供日志

已订正

**Comment by xiahuaijia** [comment]
1. 请详细描述
> 点击 ‘下载全部’
> 待下载四个、五个左右时出现错误

2. 请按要求提供完整日志

**Comment by YongQI233** [comment]
> 1. 请详细描述
> 
> > 点击 ‘下载全部’
> > 待下载四个、五个左右时出现错误
> 
> 2. 请按要求提供完整日志

完整日志已在log区提供，且分为了四段

**Comment by xiahuaijia** [comment]
> > 1. 请详细描述
> > 
> > > 点击 ‘下载全部’
> > > 待下载四个、五个左右时出现错误
> > 
> > 
> > 
> > 2. 请按要求提供完整日志
> 
> 完整日志已在log区提供，且分为了四段

日志不完整, 请先认真 阅读日志获取方法

**Comment by YongQI233** [comment]
如何反馈
日志是解决问题的关键, 以下反馈并不能找到问题原因

一张图片
一句话
发问号 ???

1.视频链接编号
2.操作流程
3.日志

我认为已依照次方法进行更正，如有更多错误，请您指出

**Comment by YongQI233** [comment]
> > > 1. 请详细描述
> > > 
> > > > 点击 ‘下载全部’
> > > > 待下载四个、五个左右时出现错误
> > > 
> > > 
> > > 
> > > 2. 请按要求提供完整日志
> > 
> > 
> > 完整日志已在log区提供，且分为了四段
> 
> 日志不完整, 请先认真 阅读日志获取方法

我**已意识到**我的**错误**，但JiThon没有配置文件，不知如何进入de-bug模式。请您指出，还望谅解。

**Comment by YongQI233** [comment]
JiThon的目录结构如下：
Jithon_3.1_Beta.exe
resources
-  JiJiDownCore-win64.exe
-  ffmpeg.exe
temp
-  log日志文件

**Comment by KalunJ** [comment]
**重现**
重现此行为的步骤:

1. jithon下载合集或者up投稿大批量任务时
2. jithon解析后点击下载全部
3. jithon推送任务到核心
4. 下载几个视频后jithon报错，核心崩溃，下面为jithon生成的核心日志

相关核心日志
https://pastebin.com/vTTByCeA

**Comment by YongQI233** [comment]
> **重现** 重现此行为的步骤:
> 
> 1. jithon下载合集或者up投稿大批量任务时
> 2. jithon解析后点击下载全部
> 3. jithon推送任务到核心
> 4. 下载几个视频后jithon报错，核心崩溃，下面为jithon生成的核心日志
> 
> 相关核心日志 https://pastebin.com/vTTByCeA

感谢，我是一个没读明白帮助文档的小笨蛋 aaa

**Comment by xiahuaijia** [comment]
请提供完整日志, 日志内容与问题描述不符.

如果是调用核心请提供调用接口和可复现调用参数. 请勿在问题描述中添加无意义图片

**Comment by xiahuaijia** [comment]
未在时限内提供有效日志, 问题关闭
