### ISSUE TITLE
打开唧唧down出现两条报错且无法连接唧唧down核心

### ISSUE THREAD

**Issue by LookGH803** [JiJiDown/Tracker#27]
**描述错误**
打开唧唧down UI出现两条报错
无法连接唧唧down核心

**软件信息**

 - 你使用的是什么系统: Windows11专业工作站版 22631.3593
 - 软件版本号: git.r306.962db85b

**重现**
重现此行为的步骤:

1. 打开唧唧 Down UI，显示报错
1. 右击快捷方式“唧唧 Down UI”
2. 点击“以管理员身份启动”
3. 看到错误，弹窗显示如下
（1）
JiJiDown.Core.SDK.dll 无法与 JiJiDownCore 通讯
1.检查 JiJiDownCore 是否还在运行
2.检查端口是否监听成功
3.检查配置文件
（2）
JiJiDownCore connection error
无法与唧唧核心通讯
检查核心是否还在运行
4. 以管理员方式打开“唧唧down”核心，只有闪过一个弹窗没其他反应

**预期行为**
软件安装不是默认的C盘
安装的时候已经把1.0版本卸载

**附加日志**

```log
time="2024-05-20 02:23:30" level=info msg="Welcome to JiJiDownCore git.r306.962db85b windows/amd64 with go1.22.3"
time="2024-05-20 02:23:30" level=info msg="Built on 2024-05-14 23:50:54"
time="2024-05-20 02:23:30" level=info msg="Copyright 2014-2024 - JiJiDown.com"
time="2024-05-20 02:23:30" level=info msg="Configuration file location: C:\\Users\\lookgh0000\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2024-05-20 02:23:30" level=fatal msg="Parse config error: session-workers range must be between 1-3"

```

辛苦各位开发者，提前感谢！！！

**Comment by xiahuaijia** [comment]
配置文件相关问题请浏览这个 [配置文件](http://client.jijidown.com/quick_start/configuration/)

[JiJiDown.Core.SDK.dll 无法与 JiJiDownCore 通讯](http://client.jijidown.com/support/faq/#issue_1) 请检查这个, 端口号需要更换为 4000, 4100, 64001

**Comment by LookGH803** [comment]
收到，最终解决方法是把config.yaml删除然后重装软件，十分顺利
感谢帮助，感激不尽

**Comment by zheyu-U** [comment]
疑似由 Jithon_3.2.1_Beta_Fix.exe 修改 config.yaml 引起。  
启动 Jithon_3.2.1_Beta_Fix.exe 前 config.yaml 正常，JiJiDownCore 正常运行。 
  config.yaml 内容如下：
```yaml
log-level: warning
external-controller-port:
    grpc: 4000
    grpc-web: 4100
    restful-api: 64001
download-task:
    max-task: 2
    download-speed-limit: 0
jdm:
    max-retry: 5
    retry-wait: 10
    session-workers: 1
    part-workers: 5
    min-split-size: 5
    proxy-addr: ""
    check-best-mirror: true
    cache-in-ram: false
    cache-in-ram-limit: 500
    insecure-skip-verify: false
    custom-root-certificates: ""

```   
启动 Jithon_3.2.1_Beta_Fix.exe 后Jithon报错，Jithon报错如下  
```
(base) PS C:\Program Files\JiJiDown> .\Jithon_3.2.1_Beta_Fix.exe
2025-07-05 14:20:48.906 | INFO     | core:<module>:49 - 启动grpc,地址为localhost:64000
2025-07-05 14:20:48.906 | INFO     | core:<module>:51 - 设置SDK
2025-07-05 14:20:48.911 | INFO     | core:<module>:55 - 设置路径
2025-07-05 14:20:48.969 | INFO     | __main__:<module>:605 - 当前是管理员权限
2025-07-05 14:20:48.970 | INFO     | __main__:<module>:606 - 自动更新核心
2025-07-05 14:20:48.975 | INFO     | core:get_sha265:364 - 获取云端核心数据,检查更新
2025-07-05 14:20:49.203 | INFO     | core:update_core:441 - 核心目前是最新版本
2025-07-05 14:20:49.203 | INFO     | core:check_ffmpeg:62 - ffmpeg存在
2025-07-05 14:20:49.203 | INFO     | __main__:<module>:609 - 生成配置文件
2025-07-05 14:20:49.203 | INFO     | __main__:<module>:613 - 主程序启动,如未自动跳转请打开http://127.0.0.1:8080
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 614, in <module>
  File "core.py", line 103, in notify
  File "core.py", line 202, in lanzou_api
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[16496] Failed to execute script 'app' due to unhandled exception!
```
 config.yaml被修改成如下：
``` yaml
portable: false
log-level: debug
external-controller: 127.0.0.1:64000
external-ui: ""
secret: ""
user-info:
    raw-access-token: ""
    raw-cookies: ""
    hide-nickname: false
download-task:
    temp-dir: ""
    download-dir: C:\Program Files\JiJiDown
    ffmpeg-path: ""
    max-task: 3
    download-speed-limit: 1
    disable-mcdn: true
jdm:
    max-retry: 0
    retry-wait: 0
    jdm-task-workers: 0
    session-workers: 0
    min-split-size: 0
    proxy-addr: ""
    check-best-mirror: true
    cache-in-ram: false
    cache-in-ram-limit: 0
    insecure-skip-verify: false
    certs-file-path: ""
```
此后 JiJiDownCore 打开闪退，并报错：

> Parse config error: session-workers range must be between 1-3

**Comment by xiahuaijia** [comment]
问题已解决, 关闭此问题
